### ISSUE TITLE
bug assignment in condition

### ISSUE THREAD

**Issue by rleddy** [NitrofMtl/weeklyAlarm#2]
on line 135 of weeklyAlarm.cpp

if ( alm->nextAlarm = &alarm ) {

That assigns the address of the alarm to the next alarm. 
I think you want:
if ( alm->nextAlarm == &alarm ) {

**Comment by NitrofMtl** [comment]
You're right. Thank you.

This been fix on version 4.0.4

Regards!
 Nitrof
