### ISSUE TITLE
Upper and lower case of the header file is different

### ISSUE THREAD

**Issue by m7b** [NitrofMtl/weeklyAlarm#3]
The header file (weeklyAlarm.h) is lower case with the first letter. But it is included with a capital first letter.

Noticed when compiling with Linux.

.piolibdeps/WeeklyAlarm_ID5745/src/**w**eeklyAlarm.cpp:1:25: fatal error: **W**eeklyAlarm.h: No such file or directory

**Comment by NitrofMtl** [comment]
Fixed.
