### ISSUE TITLE
spelling

### ISSUE THREAD

**Issue by peterjazenga** [NitrofMtl/weeklyAlarm#6]
Saturday was incorrectly spelled, the corrected line is shown below

enum class AlarmType : uint8_t {SUNDAY, MONDAY, TUESDAY, WEDNESDAY, THURSDAY, FRIDAY,SATURDAY, WEEK,  WEEK_END, ALL_DAYS};

**Comment by NitrofMtl** [comment]
Fix on v4.0.5

Thanks.
